# Change these first
owner: ceubri # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: whynotprod
    url: https://www.whynotprod.com/
  - name: Adeline vous coiffe
    url: https://adelinevouscoiffe.fr/
  - name: Cmettavant
    url: https://cmettavant.fr/
  - name: Test Broken Site
    url: https://cettesitedunimportequoiextravagant.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WhynotPROD Status
  introTitle: "WhynotPROD - Suivi des services"
  introMessage: Page de statut en temps réel pour le suivi de la disponibilité de nos sites web et applications.
  navbar:
    - title: Status
      href: /upptime/
    - title: GitHub
      href: https://github.com/ceubri/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
